/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.pdf;

import com.openbravo.basic.BasicException;
import com.openbravo.beans.JCalendarDialog;
import com.openbravo.format.Formats;
import com.openbravo.pos.reports.params.JParamsStartAndEndDatesInterval;
import java.awt.BorderLayout;
import java.io.File;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import mvc.controller.SalesRegistryWorker;
import org.ofbiz.base.util.Debug;
import org.ofbiz.base.util.UtilValidate;
import org.ofbiz.ordermax.base.BaseHelper;
import org.ofbiz.ordermax.base.ControllerOptions;
import org.ofbiz.ordermax.product.productloader.ProductDataTreeLoader;
import org.ofbiz.ordermax.entity.SalesRegister;

/**
 *
 * @author BBS Auctions
 */
public class SalesRegisterUpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesRegisterUpdatePanel
     */
    org.icepdf.ri.common.SwingController controller = null;
    SalesRegister reg = null;

    public SalesRegisterUpdatePanel(String trxId) {
        initComponents();
        getPdfViewContainer();
        reg = SalesRegistryWorker.getSalesRegister(trxId, ControllerOptions.getSession());
        if (reg != null && controller != null) {
            setDialogFields();
            //  try {
            String path = ProductDataTreeLoader.InvoicePdfFilePath;
            if (UtilValidate.isNotEmpty(reg.getPartyId())) {
                path = path.concat(reg.getPartyId()).concat("\\");
            }
            path = path.concat(reg.getRelatedId()).concat(".pdf");
            File myFile = new File(path);//new File("C:\\ofbiz\\ofbiz-12.04.02\\applications\\content\\data\\pdftest.pdf");

            //Desktop.getDesktop().open(myFile);
            controller.openDocument(myFile.getAbsolutePath());
            //   } catch (IOException ex) {
            //e
            //   }
        }
    }

    void setDialogFields() {
        if (reg != null) {
            txtPartyId.setText(reg.getPartyId());
            //reg.setTrxTypeId("SALES_INVOICE");
            txtInvoiceNo.setText(reg.getRelatedId());
            if (reg.getAmount() != null) {
                txtInvoiceAmount.setText(reg.getAmount().toString());
            }
            if (reg.getBalanceamount() != null) {
                txtBalanceAmount.setText(reg.getBalanceamount().toString());
            }
            if (reg.getTrxDate() != null) {
                jTxtStartDate.setText(reg.getTrxDate().toString());
            }
        }
    }

    void getDialogFields() {
        // SalesRegister salesRegister = new SalesRegister();
        if (reg != null) {
            //reg.setPartyId(panelPartyPickerEditPanel.getValue());
            reg.setTrxTypeId("SALES_INVOICE");
            //reg.setRelatedId(txtInvoiceNo.getText());
            reg.setAmount(new BigDecimal(txtInvoiceAmount.getText()));
            reg.setBalanceamount(new BigDecimal(txtBalanceAmount.getText()));
            reg.setTrxDate(getDate());
        }
    }

    public Timestamp getDate() {

        try {
            Timestamp fromDate = null;

            Object startdate = Formats.TIMESTAMP.parseValue(jTxtStartDate.getText());
            if (startdate != null) {
                fromDate = new Timestamp(((java.util.Date) startdate).getTime());
            }
            return fromDate;

        } catch (BasicException ex) {
            Logger.getLogger(JParamsStartAndEndDatesInterval.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSourceFilePdf = new javax.swing.JTextField();
        btnSmallIcon2 = new javax.swing.JButton();
        pdfPanelPartyId = new javax.swing.JPanel();
        txtPartyId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtInvoiceNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTxtStartDate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txtInvoiceAmount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txtBalanceAmount = new javax.swing.JTextField();
        btnDateStart = new javax.swing.JButton();
        btnRenameandMove = new javax.swing.JButton();
        lblCaption = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txtTraxId = new javax.swing.JTextField();
        pdfPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel5.setLayout(null);

        jLabel4.setText("Load File:");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(12, 17, 56, 16);

        txtSourceFilePdf.setPreferredSize(new java.awt.Dimension(6, 26));
        jPanel5.add(txtSourceFilePdf);
        txtSourceFilePdf.setBounds(10, 40, 200, 26);

        btnSmallIcon2.setText("jButton1");
        btnSmallIcon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmallIcon2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnSmallIcon2);
        btnSmallIcon2.setBounds(210, 40, 35, 25);

        pdfPanelPartyId.setBackground(new java.awt.Color(255, 255, 204));

        txtPartyId.setText("jTextField1");

        javax.swing.GroupLayout pdfPanelPartyIdLayout = new javax.swing.GroupLayout(pdfPanelPartyId);
        pdfPanelPartyId.setLayout(pdfPanelPartyIdLayout);
        pdfPanelPartyIdLayout.setHorizontalGroup(
            pdfPanelPartyIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPartyId, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pdfPanelPartyIdLayout.setVerticalGroup(
            pdfPanelPartyIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdfPanelPartyIdLayout.createSequentialGroup()
                .addComponent(txtPartyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel5.add(pdfPanelPartyId);
        pdfPanelPartyId.setBounds(10, 100, 200, 25);

        jLabel9.setText("Party:");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(10, 70, 34, 16);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtInvoiceNo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(txtInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8);
        jPanel8.setBounds(10, 150, 200, 25);

        jLabel10.setText("Invoice No:");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 130, 64, 16);

        jLabel11.setText("Date");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 180, 26, 16);

        jTxtStartDate.setMinimumSize(new java.awt.Dimension(6, 25));
        jTxtStartDate.setPreferredSize(new java.awt.Dimension(6, 25));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.add(jPanel9);
        jPanel9.setBounds(10, 200, 200, 25);

        jLabel12.setText("Invoice Amount");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 230, 88, 16);

        txtInvoiceAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtInvoiceAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(txtInvoiceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel10);
        jPanel10.setBounds(10, 250, 200, 25);

        jLabel13.setText("Balance Amount");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 280, 92, 16);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBalanceAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(txtBalanceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel11);
        jPanel11.setBounds(10, 300, 200, 25);

        btnDateStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/date.png"))); // NOI18N
        btnDateStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateStartActionPerformed(evt);
            }
        });
        jPanel5.add(btnDateStart);
        btnDateStart.setBounds(210, 200, 30, 25);

        btnRenameandMove.setText("Save");
        btnRenameandMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenameandMoveActionPerformed(evt);
            }
        });
        jPanel5.add(btnRenameandMove);
        btnRenameandMove.setBounds(10, 390, 61, 25);

        lblCaption.setBackground(new java.awt.Color(255, 255, 204));
        lblCaption.setOpaque(true);
        jPanel5.add(lblCaption);
        lblCaption.setBounds(200, 390, 80, 20);

        jLabel14.setText("Trx Id:");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(10, 330, 39, 16);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTraxId, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(txtTraxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel12);
        jPanel12.setBounds(10, 350, 200, 25);

        jPanel4.add(jPanel5, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout pdfPanelLayout = new javax.swing.GroupLayout(pdfPanel);
        pdfPanel.setLayout(pdfPanelLayout);
        pdfPanelLayout.setHorizontalGroup(
            pdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        pdfPanelLayout.setVerticalGroup(
            pdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jPanel4.add(pdfPanel, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSmallIcon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmallIcon2ActionPerformed
        File file = BaseHelper.getImageFilePath("Invoice Source Location");
        if (file != null) {
            txtSourceFilePdf.setText(file.getAbsolutePath());
            controller.openDocument(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnSmallIcon2ActionPerformed

    void saveSalesRegistry(String partyId, String relatedId, BigDecimal amount, BigDecimal balace, Timestamp date) {
        SalesRegister salesRegister = new SalesRegister();
        salesRegister.setPartyId(partyId);
        salesRegister.setTrxTypeId("SALES_INVOICE");
        salesRegister.setRelatedId(relatedId);
        salesRegister.setAmount(amount);
        salesRegister.setBalanceamount(balace);
        salesRegister.setTrxDate(date);
        SalesRegistryWorker.createOrUpdateSalesRegister(salesRegister, ControllerOptions.getSession());
    }

    private void txtInvoiceAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceAmountActionPerformed

    private void btnDateStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateStartActionPerformed

        Date date;
        try {
            date = (Date) Formats.TIMESTAMP.parseValue(jTxtStartDate.getText());
        } catch (BasicException e) {
            date = null;
        }
        date = JCalendarDialog.showCalendarTimeHours(this, date);
        if (date != null) {
            jTxtStartDate.setText(Formats.TIMESTAMP.formatValue(date));
        }
    }//GEN-LAST:event_btnDateStartActionPerformed

    private void btnRenameandMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenameandMoveActionPerformed
        try {
            if (reg != null) {
                getDialogFields();
                reg.getGenericValue();
                SalesRegistryWorker.createOrUpdateSalesRegister(reg, ControllerOptions.getSession());
            }
        } catch (Exception e) {
            Debug.logError(e, "module");
        }
        /*if (UtilValidate.isNotEmpty(txtInvoiceNo.getText()) && UtilValidate.isNotEmpty(panelPartyPickerEditPanel.getValue())) {
         GenericValue partyGenric = null;
         String partyId = panelPartyPickerEditPanel.getValue();
         try {

         partyGenric = ControllerOptions.getSession().getDelegator().findByPrimaryKey("Party", UtilMisc.toMap("partyId", partyId));
         } catch (GenericEntityException e) {
         Debug.logWarning(e.getMessage(), module);
         }

         if (partyGenric != null) {
         try {
         String newFilePath = getUniqueFileName(txtDestinationDir.getText(),
         panelPartyPickerEditPanel.getValue(), txtInvoiceNo.getText(), 0);
         FileUtils.getFileUtils().copyFile(txtSourceFilePdf.getText(), newFilePath);

         SalesRegister salesRegister = new SalesRegister();
         salesRegister.setPartyId(panelPartyPickerEditPanel.getValue());
         salesRegister.setTrxTypeId("SALES_INVOICE");
         salesRegister.setRelatedId(txtInvoiceNo.getText());
         salesRegister.setAmount(new BigDecimal("0"));
         salesRegister.setBalanceamount(new BigDecimal("0"));

         salesRegister.setTrxDate(getDate());

         SalesRegistryWorker.createOrUpdateSalesRegister(salesRegister, ControllerOptions.getSession());

         //Files.move(file, newFile, StandardCopyOption.REPLACE_EXISTING);
         } catch (IOException ex) {
         Logger.getLogger(PdfFileViewerPanel.class.getName()).log(Level.SEVERE, null, ex);
         }        // TODO add your handling code here:
         if (fileList.getModel().getSize() > (index + 1)) {
         index = index + 1;
         String filePath = (String) fileList.getModel().getElementAt(index);
         txtSourceFilePdf.setText(filePath);
         controller.openDocument(filePath);
         }
         if (currFileName != null) {
         try {
         FileUtils.getFileUtils().rename(new File(currFileName), new File(txtSourceFile.getText() + "\\" + txtInvoiceNo.getText() + ".pdf"));
         } catch (IOException ex) {
         Logger.getLogger(PdfFileViewerPanel.class.getName()).log(Level.SEVERE, null, ex);
         }
         currFileName = (String) fileList.getModel().getElementAt(index);
         txtInvoiceNo.setText("");
         txtInvoiceNo.requestFocus();
         if (!cbSorted.isSelected()) {
         panelPartyPickerEditPanel.textIdField.setText("");
         panelPartyPickerEditPanel.textIdField.requestFocus();
         }

         }
         } else {
         OrderMaxOptionPane.showMessageDialog(null, "Party doesn't exists: " + partyId);
         }
         } else {
         OrderMaxOptionPane.showMessageDialog(null, "Party or Invoice number empty: ");
         }

         setCaption();*/
    }//GEN-LAST:event_btnRenameandMoveActionPerformed

    void getPdfViewContainer() {
        // Get a file from the command line to open
        // String filePath = "C:\\ofbiz\\ofbiz-12.04.02\\applications\\content\\data\\MACI22733.pdf";

        // build a component controller
        controller = new org.icepdf.ri.common.SwingController();
        controller.setIsEmbeddedComponent(true);

        org.icepdf.ri.util.PropertiesManager properties = new org.icepdf.ri.util.PropertiesManager(
                System.getProperties(),
                ResourceBundle.getBundle(org.icepdf.ri.util.PropertiesManager.DEFAULT_MESSAGE_BUNDLE));

        properties.set(org.icepdf.ri.util.PropertiesManager.PROPERTY_DEFAULT_ZOOM_LEVEL, "1.75");

        org.icepdf.ri.common.SwingViewBuilder factory = new org.icepdf.ri.common.SwingViewBuilder(controller, properties);

        // add interactive mouse link annotation support via callback
        controller.getDocumentViewController().setAnnotationCallback(
                new org.icepdf.ri.common.MyAnnotationCallback(controller.getDocumentViewController()));
        JPanel viewerComponentPanel = factory.buildViewerPanel();
        // JFrame applicationFrame = new JFrame();
        //applicationFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pdfPanel.setLayout(new BorderLayout());
        pdfPanel.add(viewerComponentPanel, BorderLayout.CENTER);
        // Now that the GUI is all in place, we can try openning a PDF
        // controller.openDocument(filePath);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDateStart;
    private javax.swing.JButton btnRenameandMove;
    private javax.swing.JButton btnSmallIcon2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTxtStartDate;
    private javax.swing.JLabel lblCaption;
    private javax.swing.JPanel pdfPanel;
    private javax.swing.JPanel pdfPanelPartyId;
    private javax.swing.JTextField txtBalanceAmount;
    private javax.swing.JTextField txtInvoiceAmount;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JTextField txtPartyId;
    private javax.swing.JTextField txtSourceFilePdf;
    private javax.swing.JTextField txtTraxId;
    // End of variables declaration//GEN-END:variables
}
