/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ofbiz.ordermax.product.panel;

import java.awt.BorderLayout;
import org.ofbiz.ordermax.base.DatePickerEditPanel;
import org.ofbiz.ordermax.utility.ComponentBorder;

/**
 *
 * @author siranjeev
 */
public class PanelDates extends javax.swing.JPanel {
    private DatePickerEditPanel editOrderDate = null;
    private DatePickerEditPanel editEntryDate = null;
    private DatePickerEditPanel txtLineItemOrderDate = null;
    private DatePickerEditPanel txtLineItemEntryDate = null;

    /**
     * Creates new form PanelDates
     */
    public PanelDates() {
        initComponents();
        editOrderDate = new DatePickerEditPanel();
//        editOrderDate.setSession(session);
        panelIntroductionDate.setLayout(new BorderLayout());
        panelIntroductionDate.add(BorderLayout.CENTER, editOrderDate);

        editEntryDate = new DatePickerEditPanel();
//        editEntryDate.setSession(session);
        panelReleaseDate.setLayout(new BorderLayout());
        panelReleaseDate.add(BorderLayout.CENTER, editEntryDate);

        txtLineItemOrderDate = new DatePickerEditPanel();
//        txtLineItemOrderDate.setSession(session);
        panelDiscontinuation.setLayout(new BorderLayout());
        panelDiscontinuation.add(BorderLayout.CENTER, txtLineItemOrderDate);

        txtLineItemEntryDate = new DatePickerEditPanel();
//        txtLineItemEntryDate.setSession(session);
        panelSupportThruDate.setLayout(new BorderLayout());
        panelSupportThruDate.add(BorderLayout.CENTER, txtLineItemEntryDate);
        

//        ComponentBorder.doubleRaisedLoweredBevelBorder(panelWordingAndComment, "Wording And Comment");

        ComponentBorder.doubleRaisedLoweredBevelBorder(panelDates, "Dates");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDates = new javax.swing.JPanel();
        panelIntroductionDate = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelReleaseDate = new javax.swing.JPanel();
        panelDiscontinuation = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        panelSupportThruDate = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout());

        panelDates.setPreferredSize(new java.awt.Dimension(749, 56));

        panelIntroductionDate.setMinimumSize(new java.awt.Dimension(100, 0));
        panelIntroductionDate.setPreferredSize(new java.awt.Dimension(0, 25));

        javax.swing.GroupLayout panelIntroductionDateLayout = new javax.swing.GroupLayout(panelIntroductionDate);
        panelIntroductionDate.setLayout(panelIntroductionDateLayout);
        panelIntroductionDateLayout.setHorizontalGroup(
            panelIntroductionDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        panelIntroductionDateLayout.setVerticalGroup(
            panelIntroductionDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Introduction Date:");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Release Date:");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        panelReleaseDate.setMinimumSize(new java.awt.Dimension(100, 0));
        panelReleaseDate.setPreferredSize(new java.awt.Dimension(0, 25));

        javax.swing.GroupLayout panelReleaseDateLayout = new javax.swing.GroupLayout(panelReleaseDate);
        panelReleaseDate.setLayout(panelReleaseDateLayout);
        panelReleaseDateLayout.setHorizontalGroup(
            panelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        panelReleaseDateLayout.setVerticalGroup(
            panelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        panelDiscontinuation.setMinimumSize(new java.awt.Dimension(100, 0));
        panelDiscontinuation.setPreferredSize(new java.awt.Dimension(0, 25));

        javax.swing.GroupLayout panelDiscontinuationLayout = new javax.swing.GroupLayout(panelDiscontinuation);
        panelDiscontinuation.setLayout(panelDiscontinuationLayout);
        panelDiscontinuationLayout.setHorizontalGroup(
            panelDiscontinuationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        panelDiscontinuationLayout.setVerticalGroup(
            panelDiscontinuationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Sales Discontinuation  Thru Date:");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        panelSupportThruDate.setMinimumSize(new java.awt.Dimension(100, 0));
        panelSupportThruDate.setPreferredSize(new java.awt.Dimension(0, 25));

        javax.swing.GroupLayout panelSupportThruDateLayout = new javax.swing.GroupLayout(panelSupportThruDate);
        panelSupportThruDate.setLayout(panelSupportThruDateLayout);
        panelSupportThruDateLayout.setHorizontalGroup(
            panelSupportThruDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        panelSupportThruDateLayout.setVerticalGroup(
            panelSupportThruDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Support Thru Date:");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panelDatesLayout = new javax.swing.GroupLayout(panelDates);
        panelDates.setLayout(panelDatesLayout);
        panelDatesLayout.setHorizontalGroup(
            panelDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIntroductionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDiscontinuation, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSupportThruDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        panelDatesLayout.setVerticalGroup(
            panelDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(panelIntroductionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(panelReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDiscontinuation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(panelSupportThruDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(panelDates);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel panelDates;
    private javax.swing.JPanel panelDiscontinuation;
    private javax.swing.JPanel panelIntroductionDate;
    private javax.swing.JPanel panelReleaseDate;
    private javax.swing.JPanel panelSupportThruDate;
    // End of variables declaration//GEN-END:variables
}
