/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.report;

import javax.swing.Icon;

/**
 *
 * @author BBS Auctions
 */
public class ReportSelectionContainer extends javax.swing.JPanel {
    private Icon menu_open;
    private Icon menu_close;
    /**
     * Creates new form ReportSelectionContainer
     */
    public ReportSelectionContainer() {
        initComponents();
       /* if (jButton2.getComponentOrientation().isLeftToRight()) {
            menu_open = new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/1rightarrow.png"));
            menu_close = new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/1leftarrow.png"));
        } else {
            menu_open = new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/menu-left.png"));
            menu_close = new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/menu-right.png"));
        }*/
        assignMenuButtonIcon();        
    }
    
    public void setMenuVisible(boolean value) {

        m_jPanelLeft.setVisible(value);
        assignMenuButtonIcon();
        revalidate();
    }

    private void assignMenuButtonIcon() {
 //       jButton2.setIcon(m_jPanelLeft.isVisible()
 //               ? menu_close
 //               : menu_open);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jPanelLeft = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());
        add(m_jPanelLeft, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel m_jPanelLeft;
    // End of variables declaration//GEN-END:variables
}
