/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ofbiz.ordermax.screens.action;

/**
 *
 * @author siranjeev
 */
public enum ActionType {
    SALESORDER, 
    ARINVOICE, 
    RETURN,
    CREATE_PAYMENT_ACTION,
    SALESQUOTE,
    CLIENTACTION,
    PRODUCTACTION,
    PRODUCT_MAINTAIN_ACTION,
    PRODUCT_ENQUIRE_ACTION,    
    PURCHASEORDER,  
    SUPPLIERCLIENTACTION,
    LISTPRICE_LOOKUP_ACTION,
    LASTPRICE_LOOKUP_ACTION,
    GENERICPRICE_LOOKUP_ACTION,
    SHIPMENT_RECEIPT_ACTION,
    SUPPLIERPRODUCT_LOOKUP_ACTION,
    IMPORT_DATA_ACTION,
    PRODUCT_CATEGORY_MAINTAIN_ACTION,
    GENERATE_INVOICE_FROM_ORDERACTION,
    GENERATE_PURCHASE_INVOICE_FROM_ORDERACTION,
    ORDER_LIST_ACTION,
    PURCHASE_INVOICE_LIST_ACTION,    
    PRINT_PURCHASE_INVOICE_ACTION,
    PRINT_PURCHASE_PICKSLIP_ACTION,
    PRINT_PICKSLIP_ACTION,    
    APPROVE_PURCHASE_ORDER_ACTION,
    APPROVE_PURCHASE_INVOICE_ACTION,
    CANCEL_PURCHASE_ORDER_ACTION,
    VIEWEDIT_DELIVER_SCHEDULEINFO_ACTION,
    CREATE_NEW_SHIPGROUP_ACTION,
    CREATE_AS_NEW_ORDER_ACTION,
    VIEW_ORDER_HISTORY_ACTION,
    QUICK_REFUND_ENTIRE_ORDER_ACTION,
    CREATE_RETURN_ACTION,
    CREATE_REPLACEMENT_ORDER_ACTION,
    PAY_PURCHASE_ORDER_ACTION,
    QUICKSHIP_ENTIRE_ORDER_ACTION,
    EDIT_PURCHASE_INVOICE_ACTION,
    EDIT_SALES_INVOICE_ACTION,    
    CUSTOMER_PAYMENT_LIST_ACTION,
    ORDER_RETURN_LIST_ACTION,    
    SUPPLIER_PAYMENT_LIST_ACTION,
    CUSTOMER_PAYMENT_ACTION,    
    CREATE_NEW_PAYMENT_ACTION,    
    SAVE_POSTALADDRESS_ACTION,
    DELETE_POSTALADDRESS_ACTION,
    INVENTORY_ITEM_LIST_ACTION,        
    INVENTORY_ITEM_DETAIL_LIST_ACTION,
    PRODUCT_PRICING_LIST_ACTION,
    SUPPLIER_PRODUCTL_LIST_ACTION,
    CUSTOMER_FIND_LIST_ACTION,
    SUPPLIER_FIND_LIST_ACTION,   
    POS_PANEL_DESIGN_ACTION,
    PRODUCT_PRINT_LABEL_ACTION,
}
