/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.screens;

import org.ofbiz.ordermax.entity.PostalAddress;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.ofbiz.entity.GenericValue;

/**
 *
 * @author siranjeev
 */
public class AddressPanel extends javax.swing.JPanel {

    protected PostalAddress postalAddress = null;
    /**
     * Creates new form addressPanel
     */
    public AddressPanel() {
        initComponents();

    }

    public void setPostalAddress(GenericValue val) {
        postalAddress = new PostalAddress(val);
        try {
            postalAddress.setGenericValue();
        } catch (Exception ex) {
            Logger.getLogger(AddressPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        setUIFields();
    }
    public void setUIFields() {
        editcontactMechId.setText(postalAddress.getContactMechId());
        edittoName.setText(postalAddress.getToName());
        editattnName.setText(postalAddress.getAttnName());
        editaddress1.setText(postalAddress.getAddress1());
        editaddress2.setText(postalAddress.getAddress2());
//        editdirections.setText(postalAddress.getDirections());
        editcity.setText(postalAddress.getCity());
        editpostalCode.setText(postalAddress.getPostalCode());
//        editpostalCodeExt.setText(postalAddress.getpostalCodeExt());
        editcountryGeoId.setText(postalAddress.getcountryGeoId());
        editstateProvinceGeoId.setText(postalAddress.getstateProvinceGeoId());
//        editcountyGeoId.setText(postalAddress.getcountyGeoId());
//        editpostalCodeGeoId.setText(postalAddress.getpostalCodeGeoId());
//        editgeoPointId.setText(postalAddress.getgeoPointId());
    }

    public void getUIFields() {
        postalAddress.setContactMechId(editcontactMechId.getText());
        postalAddress.setToName(edittoName.getText());
        postalAddress.setAttnName(editattnName.getText());
        postalAddress.setAddress1(editaddress1.getText());
        postalAddress.setAddress2(editaddress2.getText());
  //      postalAddress.setDirections(editdirections.getText());
        postalAddress.setCity(editcity.getText());
        postalAddress.setpostalCode(editpostalCode.getText());
  //      postalAddress.setpostalCodeExt(editpostalCodeExt.getText());
        postalAddress.setcountryGeoId(editcountryGeoId.getText());
        postalAddress.setstateProvinceGeoId(editstateProvinceGeoId.getText());
  //      postalAddress.setcountyGeoId(editcountyGeoId.getText());
  //      postalAddress.setpostalCodeGeoId(editpostalCodeGeoId.getText());
  //      postalAddress.setgeoPointId(editgeoPointId.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel2 = new javax.swing.JLabel();
        edittoName = new javax.swing.JTextField();
        surnameLabel2 = new javax.swing.JLabel();
        editattnName = new javax.swing.JTextField();
        firstNameLabel3 = new javax.swing.JLabel();
        editaddress1 = new javax.swing.JTextField();
        surnameLabel3 = new javax.swing.JLabel();
        editaddress2 = new javax.swing.JTextField();
        surnameLabel4 = new javax.swing.JLabel();
        editcity = new javax.swing.JTextField();
        surnameLabel7 = new javax.swing.JLabel();
        editpostalCode = new javax.swing.JTextField();
        maritalStatusLabel2 = new javax.swing.JLabel();
        maritalStatusLabel3 = new javax.swing.JLabel();
        firstNameLabel4 = new javax.swing.JLabel();
        editcontactMechId = new javax.swing.JTextField();
        editcountryGeoId = new javax.swing.JTextField();
        editstateProvinceGeoId = new javax.swing.JTextField();

        firstNameLabel2.setText("Tel:"); // NOI18N

        surnameLabel2.setText("Tel 2:"); // NOI18N

        firstNameLabel3.setText("Fax:"); // NOI18N

        surnameLabel3.setText("Address:"); // NOI18N

        surnameLabel4.setText("Address:"); // NOI18N

        surnameLabel7.setText("City:"); // NOI18N

        maritalStatusLabel2.setText("Country:"); // NOI18N

        maritalStatusLabel3.setText("State:"); // NOI18N

        firstNameLabel4.setText("Id:"); // NOI18N

        editcountryGeoId.setText("jTextField1");

        editstateProvinceGeoId.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel2)
                    .addComponent(surnameLabel2)
                    .addComponent(firstNameLabel3)
                    .addComponent(surnameLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(maritalStatusLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maritalStatusLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(surnameLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(surnameLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(firstNameLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editcontactMechId, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(edittoName)
                    .addComponent(editattnName)
                    .addComponent(editaddress1)
                    .addComponent(editaddress2)
                    .addComponent(editcity)
                    .addComponent(editpostalCode)
                    .addComponent(editcountryGeoId)
                    .addComponent(editstateProvinceGeoId))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel4)
                    .addComponent(editcontactMechId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel2)
                    .addComponent(edittoName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLabel2)
                    .addComponent(editattnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel3)
                    .addComponent(editaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLabel3)
                    .addComponent(editaddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLabel4)
                    .addComponent(editcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLabel7)
                    .addComponent(editpostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maritalStatusLabel2)
                    .addComponent(editcountryGeoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maritalStatusLabel3)
                    .addComponent(editstateProvinceGeoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editaddress1;
    private javax.swing.JTextField editaddress2;
    private javax.swing.JTextField editattnName;
    private javax.swing.JTextField editcity;
    private javax.swing.JTextField editcontactMechId;
    private javax.swing.JTextField editcountryGeoId;
    private javax.swing.JTextField editpostalCode;
    private javax.swing.JTextField editstateProvinceGeoId;
    private javax.swing.JTextField edittoName;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JLabel firstNameLabel3;
    private javax.swing.JLabel firstNameLabel4;
    private javax.swing.JLabel maritalStatusLabel2;
    private javax.swing.JLabel maritalStatusLabel3;
    private javax.swing.JLabel surnameLabel2;
    private javax.swing.JLabel surnameLabel3;
    private javax.swing.JLabel surnameLabel4;
    private javax.swing.JLabel surnameLabel7;
    // End of variables declaration//GEN-END:variables
}
