/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.screens;

import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author siranjeev
 */
public class OrderMaxMdiChildForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form PartyDetailForm
     */
    public OrderMaxMdiChildForm() {
        initComponents();
    }

    public OrderMaxMdiChildForm(JPanel panel, String title) {
    super(title,true,true,false,true);        
//super(parent, modal);
        Container contentPane = this.getContentPane();
        initComponents();
        this.setSize(panel.getSize().width + 20, panel.getSize().height + 30);
        panel.setLocation(0, 0);
        contentPane.add(panel);
        this.setTitle(title);
        repaint();
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
