/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.orderbase.purchaseorder.inventory;

import org.ofbiz.ordermax.orderbase.*;
import javax.swing.JButton;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import javax.swing.plaf.basic.BasicArrowButton;

/**
 *
 * @author siranjeev
 */
public class SimpleInventoryReceiptButtonPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form ProductButtonPanel
     */
    public SimpleInventoryReceiptButtonPanel() {
        initComponents();
        this.add(new BasicArrowButton(SwingConstants.NORTH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        btnGenerateInventory = new javax.swing.JButton();
        btnPrintStickers = new javax.swing.JButton();

        okButton.setText("OK");

        btnGenerateInventory.setText("RECEIVE INVENTORY");
        btnGenerateInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateInventoryActionPerformed(evt);
            }
        });

        btnPrintStickers.setText("Print Receipt Stickers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrintStickers, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(btnGenerateInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(okButton)
                .addComponent(btnGenerateInventory)
                .addComponent(btnPrintStickers))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateInventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateInventoryActionPerformed

/*    public JButton getBtnDelete() {
        return btnDelete;
    }
*/

/*
    public JButton getBtnNewProduct() {
        return btnNewProduct;
    }

    public JButton getBtnSave() {
        return btnSave;
    }
*/
    public JButton getOkButton() {
        return okButton;
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGenerateInventory;
    public javax.swing.JButton btnPrintStickers;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

/*    public JButton getBtnLoad() {
        return btnLoad;
    }
    */
}
