/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.pospaneldesigner;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author administrator
 */
public class SkuButtonDesignPanel extends javax.swing.JPanel implements ButtonDesignPanelInterface {

    /**
     * Creates new form SkuButtonDesignPanel
     */
    public SkuButtonDesignPanel() {
        initComponents();
    }

    @Override
    public void setPanelFields(PosButton currSelBtn) {
        txtContent.setText(currSelBtn.getContent());
        txtHeight.setText(String.valueOf(currSelBtn.getH()));
        String val = currSelBtn.getName();
        if (val.indexOf(".") != -1) {
            val = val.substring(val.indexOf(".") + 1);
        }
        comboStyle.setSelectedItem(currSelBtn.getStyle());
        txtName.setText(val);
        txtWidth.setText(String.valueOf(currSelBtn.getW()));
        txtX.setText(String.valueOf(currSelBtn.getX()));
        txtY.setText(String.valueOf(currSelBtn.getY()));
        PosButtonStyles selStyle = getSelectedStyle();
        if (selStyle != null) {
            comboStyle.setBackground(Color.decode("#" + selStyle.getColorBack()));
        }
        comboDesign.setSelectedItem(currSelBtn.getAlignment());
    }
    private ArrayList<PosButtonStyles> listStyle;

    public PosButtonStyles getSelectedStyle() {
        PosButtonStyles sel = null;
        for (PosButtonStyles style : listStyle) {
            if (comboStyle.getSelectedItem().equals(style.getStyleName())) {
                return style;
            }
        }
        return sel;
    }

    @Override
    public void setStyles(ArrayList<PosButtonStyles> list) {
        comboStyle.removeAllItems();
        listStyle = list;
        for (PosButtonStyles style : list) {
            comboStyle.addItem(style.getStyleName());
        }
        comboStyle.setRenderer(new StyleComboCellRenderer(comboStyle.getRenderer(), list));
    }

    @Override
    public void getPanelFields(PosButton currSelBtn) {
        if (currSelBtn != null) {
            currSelBtn.setContent(txtContent.getText());
            currSelBtn.setH(Integer.valueOf(txtHeight.getText()));
            currSelBtn.setName("SKU." + txtName.getText());
            currSelBtn.setW(Integer.valueOf(txtWidth.getText()));
            currSelBtn.setX(Integer.valueOf(txtX.getText()));
            currSelBtn.setY(Integer.valueOf(txtY.getText()));
            PosButtonStyles selStyle = getSelectedStyle();
            if (selStyle != null) {
                currSelBtn.setStyle(selStyle.getStyleName());
            }
            currSelBtn.setAlignment(comboDesign.getSelectedItem().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtContent = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboStyle = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        comboDesign = new javax.swing.JComboBox();
        txtWidth = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtY = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText("Product Id:");

        jLabel4.setText("Display Name:");

        jLabel6.setText("Style:");

        comboStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Product", "Navigation" }));

        jLabel7.setText("Alignment:");

        comboDesign.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Center", "Left", "Right" }));

        jLabel10.setText("Width:");

        jLabel9.setText("Height:");

        jLabel8.setText("Y:");

        jLabel5.setText("X:");

        txtY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboStyle, 0, 146, Short.MAX_VALUE)
                    .addComponent(txtContent)
                    .addComponent(txtName)
                    .addComponent(comboDesign, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboDesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel6);
    }// </editor-fold>//GEN-END:initComponents

    private void txtYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYActionPerformed

    @Override
    public void setSelectionData(String id, String name) {
        txtName.setText(id);
        txtContent.setText(name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboDesign;
    private javax.swing.JComboBox comboStyle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtContent;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWidth;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    // End of variables declaration//GEN-END:variables
}
