/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.product.productContent;

import org.ofbiz.base.util.Debug;
import org.ofbiz.base.util.UtilValidate;
import org.ofbiz.ordermax.base.BaseHelper;
import org.ofbiz.ordermax.product.productloader.ProductDataTreeLoader;
import org.ofbiz.ordermax.entity.DataResource;

/**
 *
 * @author siranjeev
 */
public class PanelDataResourceImages extends javax.swing.JPanel {

    String productId;
//    protected CopyWebProductImagePanel copyWebProductImagePanel = null;

    /**
     * Creates new form PanelImages
     */
    public PanelDataResourceImages() {
        initComponents();
    }
    /*
    private ProductContentComposite productContentComposite = null;

    public ProductContentComposite getProductComposite() {
        return productContentComposite;
    }

    public void setProductComposite(ProductContentComposite productContentComposite) {
        this.productContentComposite = productContentComposite;
        setDialogField();
    }*/
    DataResource dataResource = null;

    public DataResource getDataResource() {
        return dataResource;
    }

    public void setDataResource(DataResource dataResource) {
        this.dataResource = dataResource;
        setDialogField();
    }
    
    public void clearDialogFields() {
    }

    public void setDialogField() {
        String fileName = ProductDataTreeLoader.BaseImagePath;
        if (UtilValidate.isNotEmpty(dataResource) && UtilValidate.isNotEmpty(dataResource.getobjectInfo())) {
            String filePath = fileName.concat(dataResource.getobjectInfo());
            Debug.logInfo("setDialogField: " + filePath, "test");
            originalImageUrlTextField.setText(filePath);
            showSelectandFileImage(filePath);
//                    ImageIcon icon1 = BaseHelper.getImage(filePath);
        }
        /*      Product product = productContentComposite.getProduct();
         productId = product.getproductId();
         mediumImageUrlTextField.setText(OrderMaxUtility.getValidString(product.getmediumImageUrl()));
         smallImageUrlTextField.setText(OrderMaxUtility.getValidString(product.getsmallImageUrl()));
         originalImageUrlTextField.setText(OrderMaxUtility.getValidString(product.getoriginalImageUrl()));

         largeImageUrlTextField.setText(OrderMaxUtility.getValidString(product.getlargeImageUrl()));
         detailImageUrlTextField.setText(OrderMaxUtility.getValidString(product.getdetailImageUrl()));
         if (UtilValidate.isNotEmpty(detailImageUrlTextField.getText())) {
         detailImageUrlTextField.requestFocus();
         }
         */
    }

    public void getDialogField() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        originalImageUrlTextField = new javax.swing.JTextField();
        btnOriginalIcon = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelImage.setBackground(new java.awt.Color(255, 255, 255));
        panelImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Image"));
        panelImage.setLayout(new java.awt.BorderLayout());

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        panelImage.add(lblImage, java.awt.BorderLayout.CENTER);

        add(panelImage, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Images"));

        jLabel15.setText("Original:");

        originalImageUrlTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                originalImageUrlTextFieldFocusGained(evt);
            }
        });

        btnOriginalIcon.setText("jButton1");
        btnOriginalIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOriginalIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(16, 16, 16)
                .addComponent(originalImageUrlTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOriginalIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(originalImageUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOriginalIcon))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void originalImageUrlTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_originalImageUrlTextFieldFocusGained
        showSelectandFileImage(originalImageUrlTextField.getText());
    }//GEN-LAST:event_originalImageUrlTextFieldFocusGained

    private void btnOriginalIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOriginalIconActionPerformed

        originalImageUrlTextField.setText(BaseHelper.selectandSetFileName("original", productId, 0, 0));

    }//GEN-LAST:event_btnOriginalIconActionPerformed
    protected void showSelectandFileImage(String field) {

        if (field != null && field.isEmpty() == false) {
            lblImage.setIcon(BaseHelper.getImage(field));
        } else {
            lblImage.setIcon(null);
//            copyWebProductImagePanel.imageLabelSave.setIcon(null);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOriginalIcon;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField originalImageUrlTextField;
    private javax.swing.JPanel panelImage;
    // End of variables declaration//GEN-END:variables
}
