/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.product.productContent;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import mvc.controller.LoadProductWorker;
import org.ofbiz.guiapp.xui.XuiContainer;
import org.ofbiz.ordermax.base.BaseHelper;
import org.ofbiz.ordermax.product.productloader.ProductDataTreeLoader;
import org.ofbiz.ordermax.base.components.screen.SimpleScreenInterface;
import org.ofbiz.ordermax.composite.ProductContentComposite;
import static org.ofbiz.ordermax.product.productContent.ProductContentMaintainPanel.streamDataResource;

/**
 *
 * @author BBS Auctions
 */
public class ResourceDataContentMaintainPanel extends javax.swing.JPanel implements SimpleScreenInterface {

    final public static String module = ResourceDataContentMaintainPanel.class.getName();

    /**
     * Creates new form ProdCatalogMaintainDialog
     */
    boolean isNew = true;
    boolean isModified = false;
    ContentMaintainPanel contentMaintainPanel = null;
    DataResourceMaintainPanel dataResourceMaintainPanel = null;
    PanelDataResourceImages panelImages = new PanelDataResourceImages();
    PanelDataResourceText panelText = new PanelDataResourceText();

    public ResourceDataContentMaintainPanel() {
        initComponents();

        dataResourceMaintainPanel = new DataResourceMaintainPanel();
        tabbedPaneResource.add("Data Resource", dataResourceMaintainPanel);
        contentMaintainPanel = new ContentMaintainPanel();
        tabbedPaneResource.add("Content", contentMaintainPanel);
        tabbedPaneResource.add(panelImages, "Image");
        tabbedPaneResource.add(panelText, "Text");
        
        tabbedPaneResource.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {

                if (e.getSource() instanceof JTabbedPane) {

                    JTabbedPane pane = (JTabbedPane) e.getSource();
                    if (pane.getSelectedIndex() == 0) {
//                                    
                    } else if (pane.getSelectedIndex() == 1) {
                       contentMaintainPanel.dataResourceIdPickerEditPanel.textIdField.setText(dataResourceMaintainPanel.txtDataResourceId.getText());
                    }
                    System.out.println("Selected paneNo : " + pane.getSelectedIndex());
                }
            }
        });

    }
    private ProductContentComposite productContentComposite = null;

    public ProductContentComposite getProductContentComposite() {
        return productContentComposite;
    }

    public void getDialogFields(){
        contentMaintainPanel.getDialogFields();
        dataResourceMaintainPanel.getDialogFields();
        productContentComposite.getProductContent().setcontentId(productContentComposite.getContent().getcontentId());
    }
    
    public void setProductContentComposite(ProductContentComposite productContentComposite) {
        this.productContentComposite = productContentComposite;

        contentMaintainPanel.setContent(productContentComposite.getContent());
        dataResourceMaintainPanel.setDataResource(productContentComposite.getDataResource());
        dataResourceMaintainPanel.txtDataResourceName.setText(productContentComposite.getProductContent().getproductContentTypeId());
        try {
            String dirPath = ProductDataTreeLoader.BaseImagePath;
            String fileName = streamDataResource(XuiContainer.getSession().getDelegator(), productContentComposite.getDataResource().getdataResourceId());
            boolean val = BaseHelper.isFileExists(dirPath, fileName);

        } catch (Exception ex) {
            Logger.getLogger(ProductContentMaintainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelImages.setDataResource(productContentComposite.getDataResource());
        panelText.setDataResource(productContentComposite.getDataResource());
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedPaneResource = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(tabbedPaneResource, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 30));

        btnCancel.setText("Cancel");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addGap(29, 29, 29))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnOk});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        getDialogFields();
        LoadProductWorker.saveProductContent(productContentComposite.getProductContent(), XuiContainer.getSession());
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane tabbedPaneResource;
    // End of variables declaration//GEN-END:variables
/*    @Override
     public ProductCategory getProductCategory() {
     return productCategory;
     }*/

    @Override
    public JButton getOkButton() {
        return btnOk;
    }

    @Override
    public JButton getCancelButton() {
        return btnCancel;
    }

    @Override
    public JPanel getPanel() {
        return this;
    }
}
