/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.base.components;

import com.openbravo.data.user.DirtyManager;
import javax.swing.JTextField;
import org.ofbiz.entity.GenericValue;
import org.ofbiz.ordermax.base.ControllerOptions;
import org.ofbiz.ordermax.base.components.LookupActionListnerInterface.LookupType;
import org.ofbiz.ordermax.entity.DisplayNameInterface;
import org.ofbiz.ordermax.entity.PartyNameView;
import org.ofbiz.ordermax.report.ReportCreatorSelectionInterface;

/**
 *
 * @author siranjeev
 */
public abstract class BasePickerComboPanel<E> extends javax.swing.JPanel implements ReportCreatorSelectionInterface {

    static public String module = BasePickerComboPanel.class.getName();
    ControllerOptions controllerOptions;
    DirtyManager dirty = null;
    public String originalEntityId = null;
    public String entityId = null;

    // LookupType lookupType = null;
    /**
     * Creates new form DatePickerEditPanel
     */
    public BasePickerComboPanel(ControllerOptions controllerOptions) {
        initComponents();
        //this.lookupType = lookupType;
        this.controllerOptions = controllerOptions;

        if (controllerOptions.contains("DirtyManager")) {
            dirty = (DirtyManager) controllerOptions.get("DirtyManager");
        }

        createComboAction();
    }

    protected void createComboAction() {
    }

    final void setDirtyManger(JTextField field) {
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));
        add(comboPanel);

        jLabel1.setText("jLabel1");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel comboPanel;
    protected javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
