/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.base.components;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import org.ofbiz.base.util.Debug;
import org.ofbiz.base.util.UtilValidate;
import org.ofbiz.guiapp.xui.XuiSession;
import org.ofbiz.order.shoppingcart.ShoppingCart;
import org.ofbiz.ordermax.base.ControllerOptions;
import org.ofbiz.ordermax.base.ObservingTextField;
import org.ofbiz.ordermax.utility.LookupActionListner;

/**
 *
 * @author siranjeev
 */
public class ShipGroupEditPanel extends javax.swing.JPanel {
    
    static public String module = ShipGroupEditPanel.class.getName();
    static String editorId = "OrderIdTextField";
    public String facilityId = "";
    public String contachMechId = "";
    public ShoppingCart.CartShipInfo shipInfo = null;
    /**
     * Creates new form DatePickerEditPanel
     */
    public ShipGroupEditPanel(ControllerOptions controllerOptions) {
        initComponents();
//        controllerOptions.put(editorId, textIdField);
        controllerOptions.setDoubleClickCloseDialog();
        btnHeaderPatryId.addActionListener(new LookupActionListner(LookupActionListnerInterface.LookupType.OrderId,controllerOptions));

    }
    protected XuiSession session = null;
    
    public XuiSession getSession() {
        return session;
    }
    
    public void setSession(XuiSession session) {
        this.session = session;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnHeaderPatryId = new javax.swing.JButton();
        rbAddress = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        editAddress = new javax.swing.JEditorPane();

        setPreferredSize(new java.awt.Dimension(156, 24));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 2, 0, 2, 0};
        layout.rowHeights = new int[] {0};
        setLayout(layout);

        btnHeaderPatryId.setIcon(new javax.swing.ImageIcon("C:\\backup\\ofbiz-12.04.02\\ORDER_small.png")); // NOI18N
        btnHeaderPatryId.setMinimumSize(new java.awt.Dimension(27, 27));
        btnHeaderPatryId.setPreferredSize(new java.awt.Dimension(27, 27));
        btnHeaderPatryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeaderPatryIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        add(btnHeaderPatryId, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(rbAddress, gridBagConstraints);

        editAddress.setEditable(false);
        editAddress.setContentType("text/html"); // NOI18N
        editAddress.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        editAddress.setText("<html>\n  <head>\n\n  </head>\n  <body>\nHeloo\n  </body>\n</html>\n\n");
        jScrollPane3.setViewportView(editAddress);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHeaderPatryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeaderPatryIdActionPerformed

    }//GEN-LAST:event_btnHeaderPatryIdActionPerformed
    
    private ClassLoader getClassLoader() {
        
        ClassLoader cl = null;
        try {
            cl = session.getClassLoader();
            
            if (cl == null) {
                try {
                    
                    cl = Thread.currentThread().getContextClassLoader();
                    
                } catch (Throwable t) {
                    
                }
                if (cl == null) {
                    try {
                        cl = this.getClass().getClassLoader();
                    } catch (Throwable t) {
                        Debug.logError(t, module);
                    }
                }
            }
        } catch (Exception e) {
            Debug.logError(e, module);
        }
        return cl;
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHeaderPatryId;
    public javax.swing.JEditorPane editAddress;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JRadioButton rbAddress;
    // End of variables declaration//GEN-END:variables
}
