/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.base;

import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.JTextField;


/**
 *
 * @author siranjeev
 */
public class SinglePanelContainerInternalFrame extends javax.swing.JInternalFrame implements ContainerPanelInterface {

    /**
     * Creates new form ThreePanelContainerInternalFrame
     * @param ownerName
     */
    public SinglePanelContainerInternalFrame(final String ownerName) {
        initComponents();
        this.ownerName = ownerName;
        
        setMaximizable(true);
        setIconifiable(true);
        setClosable(true);
        setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetail = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelDetail.setBackground(new java.awt.Color(204, 255, 204));
        panelDetail.setPreferredSize(new java.awt.Dimension(700, 200));
        panelDetail.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(panelDetail, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
//        this.dispose();
    }//GEN-LAST:event_formInternalFrameClosed
    public JPanel getPanelDetail() {
        return panelDetail;
    }

    public JPanel getjPanel1() {
        return panelDetail;
    }
    public JTextField textField = null;

    @Override
    public void setVisible(boolean value) {
        super.setVisible(value);
        if (textField != null) {
            textField.requestFocusInWindow();
        }
    }


    private ContainerPanelInterface.ReturnStausType returnStatus = ContainerPanelInterface.ReturnStausType.RET_CANCEL;

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public ContainerPanelInterface.ReturnStausType getReturnStatus() {
        return returnStatus;
    }

    private void doClose(ContainerPanelInterface.ReturnStausType retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    public void okButtonPressed() {
        doClose(ContainerPanelInterface.ReturnStausType.RET_OK);
    }

    public void cancelButtonPressed() {
        doClose(ContainerPanelInterface.ReturnStausType.RET_CANCEL);
    }

    protected String ownerName = null;

    public String getOwnerName() {
        return ownerName;
    }
    @Override
    public void addActionListener(ActionListener listener) {
        listeners.add(listener);
    }

    @Override
    public void removeActionListener(ActionListener listener) {
        listeners.remove(listener);
    }
    public void setCaption(String title){
            setTitle(title);    
    }
    @Override
    public ContainerType getContainerType() {
        return ContainerType.TwoPanelInternalContainer;
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelDetail;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getPanelSelecton() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setDividerLocation(int value) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public JPanel getPanelParent() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public JPanel getPanelButton() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
