/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.generic;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.ofbiz.entity.Delegator;
import org.ofbiz.entity.GenericValue;
import org.ofbiz.ordermax.base.ContainerPanelInterface;
import org.ofbiz.ordermax.base.ControllerOptions;
import org.ofbiz.ordermax.base.PosProductHelper;
import org.ofbiz.ordermax.base.components.screen.SimpleFrameMainScreen;
import org.ofbiz.ordermax.base.components.screen.SimpleScreenInterface;
import org.ofbiz.ordermax.generic.GenericValueTablePanel;
import org.ofbiz.ordermax.generic.entitypanelsimpl.EntityPanelFactory;
import org.ofbiz.ordermax.generic.entitypanelsimpl.SimpleProductStorePanel;

/**
 *
 * @author siranjeev
 */
public class GenericSelectionPanel extends javax.swing.JPanel implements SimpleScreenInterface {

    protected GenericValueTablePanel genericValueTablePanel = null;
    String entityName = "Facility";
    ControllerOptions options = null;

    /**
     * Creates new form PartyGroupDetailPanel
     */
    public GenericSelectionPanel(ControllerOptions options) {
        initComponents();
        this.options = options;
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setBounds(10, 11, 580, 200);
        if (options.contains("EntityName")) {
            entityName = (String) options.get("EntityName");
        }
        genericValueTablePanel = new GenericValueTablePanel(entityName);

        panelTerminalLog.setLayout(new BorderLayout());
        panelTerminalLog.add(BorderLayout.CENTER, genericValueTablePanel);
    }

    public GenericValue getSelectedValue() {
        return genericValueTablePanel.getSelectedGenericVal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTerminalLog = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnNewRecord = new javax.swing.JButton();
        btnEditRecord = new javax.swing.JButton();
        btnDeleteRecord = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelTerminalLog.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelTerminalLogLayout = new javax.swing.GroupLayout(panelTerminalLog);
        panelTerminalLog.setLayout(panelTerminalLogLayout);
        panelTerminalLogLayout.setHorizontalGroup(
            panelTerminalLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        panelTerminalLogLayout.setVerticalGroup(
            panelTerminalLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        add(panelTerminalLog, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(417, 60));

        btnNewRecord.setText("New");
        btnNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecordActionPerformed(evt);
            }
        });

        btnEditRecord.setText("Edit");
        btnEditRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRecordActionPerformed(evt);
            }
        });

        btnDeleteRecord.setText("Delete");

        btnOk.setText("Ok");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(btnNewRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewRecord)
                    .addComponent(btnDeleteRecord)
                    .addComponent(btnEditRecord)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecordActionPerformed

        ControllerOptions tmpOptions = new ControllerOptions(this.options);
        tmpOptions.put("X", 200);
        tmpOptions.put("Y", 0);
        // final SimplePosTerminalPanel posTerminal = new SimplePosTerminalPanel(tmpOptions);
        //final SimpleFacilityPanel posTerminal = new SimpleFacilityPanel(tmpOptions);
        //final SimpleProductStorePanel posTerminal = new SimpleProductStorePanel(tmpOptions);
        GenericSaveInterface entityPanelInterface = EntityPanelFactory.createEntityPanel(tmpOptions);
        final GenericSavePanel viewer = new GenericSavePanel(tmpOptions);
        viewer.setGenericSaveInterface(entityPanelInterface);
        viewer.add(entityPanelInterface.getPanel(), BorderLayout.CENTER);
        tmpOptions.setSimpleScreenInterface(viewer);
        final SimpleFrameMainScreen frame = SimpleFrameMainScreen.runController(tmpOptions);
        frame.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (frame.getReturnStatus().equals(ContainerPanelInterface.ReturnStausType.RET_OK)) {
                            if (viewer.getSelectedValue() != null) {
                                /* //seleVal.put("Category", viewer.selectedCategory);
                                 // GenericValue genericValue = (GenericValue) genValMap.get("Category");
                                 productIdTextField.setText(viewer.getSelectedValue().getString(lookupInterface.getKey()));
                                 productIdTextField.requestFocusInWindow();
                                 lookupInterface.setGenericValue(viewer.getSelectedValue());
                                 //notify 
                                 ActionEvent event = new ActionEvent(this, 1, "categoryId", new Date().getTime(), 2);
                                 for (ActionListener listener : listeners) {
                                 listener.actionPerformed(event); // broadcast to all
                                 }
                                 listeners.clear();
                                 Debug.logInfo(" lookup brandCategory : " + viewer.getSelectedValue().getString(lookupInterface.getKey()), module);
                                 */
                                /*
                                 panel.getOrder().addContactMech("BILLING_LOCATION", viewer.getSelectedPostalContact().getContactMech().getcontactMechId());
                                 //                                            panel.getOrder().setAllShippingContactMechId(viewer.getSelectedPostalContact().getPostalAddress().getContactMechId());
                                 panel.setDialogFields();
                                 //                                            panel.getOrder().getOrderContactList().setShippingLocationContact()
                                 Debug.logInfo("ok pressed: " + viewer.postalAddressList.getSelectedValue().getContactMechId(), module);
                                 */
                            }
                            genericValueTablePanel.loadList();
                        }
                    }
                });
    }//GEN-LAST:event_btnNewRecordActionPerformed

    private void btnEditRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRecordActionPerformed
        if (genericValueTablePanel.getSelectedGenericVal() != null) {
            ControllerOptions tmpOptions = new ControllerOptions(this.options);
            tmpOptions.put("X", 200);
            tmpOptions.put("Y", 0);

            GenericSaveInterface entityPanelInterface = EntityPanelFactory.createEntityPanel(tmpOptions);
            entityPanelInterface.setGenericValue(genericValueTablePanel.getSelectedGenericVal());
            final GenericSavePanel viewer = new GenericSavePanel(tmpOptions);
            viewer.setGenericSaveInterface(entityPanelInterface);
            viewer.add(entityPanelInterface.getPanel(), BorderLayout.CENTER);
            tmpOptions.setSimpleScreenInterface(viewer);
            final SimpleFrameMainScreen frame = SimpleFrameMainScreen.runController(tmpOptions);
            frame.addActionListener(
                    new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            if (frame.getReturnStatus().equals(ContainerPanelInterface.ReturnStausType.RET_OK)) {
                                if (viewer.getSelectedValue() != null) {
                                    /* //seleVal.put("Category", viewer.selectedCategory);
                                     // GenericValue genericValue = (GenericValue) genValMap.get("Category");
                                     productIdTextField.setText(viewer.getSelectedValue().getString(lookupInterface.getKey()));
                                     productIdTextField.requestFocusInWindow();
                                     lookupInterface.setGenericValue(viewer.getSelectedValue());
                                     //notify 
                                     ActionEvent event = new ActionEvent(this, 1, "categoryId", new Date().getTime(), 2);
                                     for (ActionListener listener : listeners) {
                                     listener.actionPerformed(event); // broadcast to all
                                     }
                                     listeners.clear();
                                     Debug.logInfo(" lookup brandCategory : " + viewer.getSelectedValue().getString(lookupInterface.getKey()), module);
                                     */
                                    /*
                                     panel.getOrder().addContactMech("BILLING_LOCATION", viewer.getSelectedPostalContact().getContactMech().getcontactMechId());
                                     //                                            panel.getOrder().setAllShippingContactMechId(viewer.getSelectedPostalContact().getPostalAddress().getContactMechId());
                                     panel.setDialogFields();
                                     //                                            panel.getOrder().getOrderContactList().setShippingLocationContact()
                                     Debug.logInfo("ok pressed: " + viewer.postalAddressList.getSelectedValue().getContactMechId(), module);
                                     */
                                }
                                genericValueTablePanel.loadList();
                            }
                        }
                    });
        }
    }//GEN-LAST:event_btnEditRecordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnDeleteRecord;
    public javax.swing.JButton btnEditRecord;
    public javax.swing.JButton btnNewRecord;
    public javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelTerminalLog;
    // End of variables declaration//GEN-END:variables

    @Override
    public JButton getOkButton() {
        return btnOk;
    }

    @Override
    public JButton getCancelButton() {
        return btnCancel;
    }

    @Override
    public JPanel getPanel() {
        return this;
    }
}
