/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ofbiz.ordermax.generic;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.ofbiz.pos.generic.GenericComboSelectionPanel;

/**
 *
 * @author siranjeev
 */
public class GenericOrderSearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form GenericPartySearchPanel
     */
    List<GenericComboSelectionPanel> filterList = new ArrayList<GenericComboSelectionPanel>();    
    public GenericOrderSearchPanel() {
        initComponents();
        GenericComboSelectionPanel genPanel = new GenericComboSelectionPanel("StatusItem", "statusId", "");
        filterList.add(genPanel);
        panelStatusId.setLayout(new BorderLayout());
        panelStatusId.add(BorderLayout.CENTER, genPanel);

        genPanel = new GenericComboSelectionPanel("PartyType", "partyTypeId", "");
        filterList.add(genPanel);
        panelPartyTypeId.setLayout(new BorderLayout());
        panelPartyTypeId.add(BorderLayout.CENTER, genPanel);
        
    }
    public Map<String, String> getSearchSelection(){
        Map<String, String> selMap = new HashMap<String, String>();
        if(textPartyId.getText() !=null && textPartyId.getText().isEmpty()==false){
            selMap.put("orderId", textPartyId.getText().toUpperCase());
        }

        if(textDescription.getText() !=null && textDescription.getText().isEmpty()==false){
            selMap.put("description", textDescription.getText().toUpperCase());
        }  
        for (GenericComboSelectionPanel genPanel : filterList) {
            if (genPanel.isAllSelected() == false) {
                selMap.put(genPanel.getSelId(), genPanel.getValue().toUpperCase());
            }
        } 
                
        return selMap;
    }
    
    public void resetSearchSelection(){
        Map<String, String> selMap = new HashMap<String, String>();
        textPartyId.setText("");
        textDescription.setText("");

        for (GenericComboSelectionPanel genPanel : filterList) {
           genPanel.setAllSelected();
        }                 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        textDescription = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textPartyId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        panelPartyTypeId = new javax.swing.JPanel();
        panelStatusId = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();

        jLabel2.setText("Description:");

        jLabel1.setText("Party Id:");

        btnSearch.setText("Search");
        btnSearch.setName(""); // NOI18N

        javax.swing.GroupLayout panelPartyTypeIdLayout = new javax.swing.GroupLayout(panelPartyTypeId);
        panelPartyTypeId.setLayout(panelPartyTypeIdLayout);
        panelPartyTypeIdLayout.setHorizontalGroup(
            panelPartyTypeIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        panelPartyTypeIdLayout.setVerticalGroup(
            panelPartyTypeIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelStatusIdLayout = new javax.swing.GroupLayout(panelStatusId);
        panelStatusId.setLayout(panelStatusIdLayout);
        panelStatusIdLayout.setHorizontalGroup(
            panelStatusIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelStatusIdLayout.setVerticalGroup(
            panelStatusIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        btnReset.setText("Reset Search");
        btnReset.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textPartyId, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(textDescription)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPartyTypeId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelStatusId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPartyTypeId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(textDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(textPartyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelStatusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {panelPartyTypeId, panelStatusId});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnReset;
    public javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel panelPartyTypeId;
    public javax.swing.JPanel panelStatusId;
    public javax.swing.JTextField textDescription;
    public javax.swing.JTextField textPartyId;
    // End of variables declaration//GEN-END:variables
}
