/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.generic;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.ofbiz.base.util.Debug;
import org.ofbiz.base.util.UtilMisc;
import org.ofbiz.base.util.UtilValidate;
import org.ofbiz.entity.Delegator;
import org.ofbiz.entity.GenericEntityException;
import org.ofbiz.entity.GenericValue;
import org.ofbiz.entity.condition.EntityCondition;
import org.ofbiz.entity.condition.EntityExpr;
import org.ofbiz.entity.condition.EntityOperator;
import org.ofbiz.entity.transaction.GenericTransactionException;
import org.ofbiz.entity.transaction.TransactionUtil;
import org.ofbiz.ordermax.base.ControllerOptions;
import org.ofbiz.ordermax.base.OrderMaxOptionPane;
import org.ofbiz.ordermax.base.components.screen.SimpleScreenInterface;

/**
 *
 * @author BBS Auctions
 */
public class GenericSavePanel extends javax.swing.JPanel implements SimpleScreenInterface {

    String entityName = null;
    static public String module = GenericSavePanel.class.getName();
    ControllerOptions options = null;

    /**
     * Creates new form GenericSavePanel
     */
    public GenericSavePanel(ControllerOptions options) {
        initComponents();
        this.options = options;
        if (options.contains("EntityName")) {
            entityName = (String) options.get("EntityName");
        }
    }

    GenericValue genericValue = null;

    public GenericValue getSelectedValue() {
        return genericValue;
    }

    public void setSelectedValue(GenericValue val) {
        genericValue = val;
    }
    private GenericSaveInterface genericSaveInterface;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSavePostalAddress = new javax.swing.JButton();
        btnDeletePostalAddress = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCopy = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(417, 50));

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSavePostalAddress.setText("Save");
        btnSavePostalAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePostalAddressActionPerformed(evt);
            }
        });

        btnDeletePostalAddress.setText("Delete");
        btnDeletePostalAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePostalAddressActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");

        btnCancel.setText("Cancel");

        btnCopy.setText("Copy");
        btnCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(btnCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSavePostalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletePostalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnDeletePostalAddress)
                    .addComponent(btnSavePostalAddress)
                    .addComponent(btnOk)
                    .addComponent(btnCancel)
                    .addComponent(btnCopy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        genericSaveInterface.newRecord();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSavePostalAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePostalAddressActionPerformed

        final ClassLoader cl = this.getClassLoader();
        
        Thread.currentThread().setContextClassLoader(cl);

        if (genericSaveInterface.hasChanged() && genericSaveInterface.isValidValues()) {

            genericSaveInterface.getDialogFields();
            
            Debug.logInfo(" Print 2", module);

            if (EntityPersistanceFactory.saveEntity(genericSaveInterface, options)) {
                genericSaveInterface.loadList(options);
            }
        }
    }//GEN-LAST:event_btnSavePostalAddressActionPerformed

    private void btnDeletePostalAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePostalAddressActionPerformed
        final ClassLoader cl = this.getClassLoader();
        Thread.currentThread().setContextClassLoader(cl);
        if (EntityPersistanceFactory.deleteEntity(genericSaveInterface, options)) {
            genericSaveInterface.loadList(options);
        }
        //}

    }//GEN-LAST:event_btnDeletePostalAddressActionPerformed

    private void btnCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyActionPerformed
        genericSaveInterface.copyRecord();
    }//GEN-LAST:event_btnCopyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnCopy;
    public javax.swing.JButton btnDeletePostalAddress;
    public javax.swing.JButton btnNew;
    public javax.swing.JButton btnOk;
    public javax.swing.JButton btnSavePostalAddress;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public JButton getOkButton() {
        return btnOk;
    }

    @Override
    public JButton getCancelButton() {
        return btnCancel;
    }

    @Override
    public JPanel getPanel() {
        return this;
    }

    public GenericSaveInterface getGenericSaveInterface() {
        return genericSaveInterface;
    }

    public void setGenericSaveInterface(GenericSaveInterface genericSaveInterface) {
        this.genericSaveInterface = genericSaveInterface;
    }

    protected ClassLoader getClassLoader() {

        ClassLoader cl = null;
        try {
            cl = ControllerOptions.getSession().getClassLoader();

            if (cl == null) {
                try {
                    cl = Thread.currentThread().getContextClassLoader();
                } catch (Throwable t) {
                    Debug.logInfo("class loader 5", module);
                }
                if (cl == null) {
                    try {
                        cl = this.getClass().getClassLoader();
                    } catch (Throwable t) {
                        Debug.logError(t, module);
                    }
                }
            }
        } catch (Exception e) {
            Debug.logError(e, module);
        }
        return cl;
    }
}
