/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.payment.sales;

import org.ofbiz.ordermax.payment.*;
import org.ofbiz.ordermax.orderbase.*;
import javax.swing.JButton;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import javax.swing.plaf.basic.BasicArrowButton;

/**
 *
 * @author siranjeev
 */
public class SimplePaymentGroupButtonPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form ProductButtonPanel
     */
    public SimplePaymentGroupButtonPanel() {
        initComponents();
        this.add(new BasicArrowButton(SwingConstants.NORTH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        btnSaveOrder = new javax.swing.JButton();
        btnStatusAction = new javax.swing.JToggleButton();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        btnSaveOrder.setText("ACCEPT  PAYMENT");

        btnStatusAction.setText("STATUS ACTION");
        btnStatusAction.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnCancel.setText("CANCEL");
        btnCancel.setMinimumSize(new java.awt.Dimension(47, 15));
        btnCancel.setPreferredSize(new java.awt.Dimension(107, 20));

        btnOk.setText("OK");
        btnOk.setMinimumSize(new java.awt.Dimension(47, 15));
        btnOk.setPreferredSize(new java.awt.Dimension(107, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaveOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStatusAction, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSaveOrder)
                    .addComponent(btnStatusAction)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

/*
    public JButton getBtnNewProduct() {
        return btnNewProduct;
    }

    public JButton getBtnSave() {
        return btnSave;
    }
*/
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnOk;
    public javax.swing.JButton btnSaveOrder;
    public javax.swing.JToggleButton btnStatusAction;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables

/*    public JButton getBtnLoad() {
        return btnLoad;
    }
    */
}
