/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.payment.paymentmethod;

import java.util.Map;
import javax.swing.JPanel;
import org.ofbiz.entity.GenericValue;
import org.ofbiz.ordermax.entity.CreditCard;
import org.ofbiz.ordermax.entity.EftAccount;
import org.ofbiz.ordermax.entity.PaymentMethod;
import org.ofbiz.ordermax.entity.PaymentMethodType;
import org.ofbiz.party.contact.ContactHelper;

/**
 *
 * @author BBS Auctions
 */
public class CreditCardPaymentPanel extends javax.swing.JPanel implements PaymentMethodInterface {

    public static final String module = CreditCardPaymentPanel.class.getName();
  //  private JGenericComboBoxSelectionModel<PaymentMethod> paymentMethodComboBox;
    //public ListComboBoxModel<PaymentMethod> comboBoxModel = new ListComboBoxModel<PaymentMethod>();
   // public JComboBox<PaymentMethod> jComboBox = new JComboBox<PaymentMethod>(comboBoxModel);
    /**
     * Creates new form EftPaymentPanel
     */
    public CreditCardPaymentPanel() {
        initComponents();
//       PaymentMethodListPanel panel = new PaymentMethodListPanel();
        //      panelPaymentMeth.setLayout(new BorderLayout());
        //      panelPaymentMeth.add(panel);
//        paymentMethodComboBox = new JGenericComboBoxSelectionModel<PaymentMethod>(comboBoxModel, jComboBox, PaymentMethodSingleton.getValueList());
//        this.add(paymentMethodComboBox.jComboBox, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtReference = new javax.swing.JTextField();
        txtComments = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCreditCardDetail = new javax.swing.JTextArea();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Credit Card Detail:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Reference:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Comments:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtAreaCreditCardDetail.setColumns(20);
        txtAreaCreditCardDetail.setRows(5);
        jScrollPane1.setViewportView(txtAreaCreditCardDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtReference, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtComments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, txtComments, txtReference});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaCreditCardDetail;
    private javax.swing.JTextField txtComments;
    private javax.swing.JTextField txtReference;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getReference() {
        return txtReference.getText();
    }

    @Override
    public String getComment() {
        return txtComments.getText();
    }

    @Override
    public void setReference(String val) {
        txtReference.setText(val);
    }

    @Override
    public void setComment(String val) {
        txtComments.setText(val);
    }

    @Override
    public void setPartyId(String partyId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    PaymentMethod payMethod = null;
    @Override
    public void setPaymentMethod(PaymentMethod payMethod) {
        this.payMethod = payMethod;     
    }

    @Override
    public PaymentMethod getPaymentMethod() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    PaymentMethodType paymentMethodType = null;

    @Override
    public void setPaymentMethodType(PaymentMethodType payMethod) {
        paymentMethodType = payMethod;
    }

    @Override
    public PaymentMethodType getPaymentMethodType() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public JPanel getPanel() {
        return this;
    }

    @Override
    public void setPaymentMethodDetails(Map<String, GenericValue> mapValues) {
        GenericValue val = mapValues.get(paymentMethodType.getpaymentMethodTypeId());
//        EftPayment eftPayment = new EftPayment(val);
    }
    CreditCard creditCard = null;
    @Override
    public void setPaymentMethodDetails(GenericValue payMethod) {
        if (payMethod != null) {
            String strPayment = ContactHelper.formatCreditCard(payMethod);
            
            creditCard = new CreditCard(payMethod);
            txtAreaCreditCardDetail.setText(strPayment);
            /*txtAccountName.setText(eftAccount.getCompanyNameOnAccount());
            txtBankName.setText(eftAccount.getBankName());
            txtRoutingNumber.setText(eftAccount.getRoutingNumber());
            txtAccountNumber.setText(eftAccount.getAccountNumber());          
                    */
        }
    }
    
}
