/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.payment.paymentmethod;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.ofbiz.ordermax.entity.DisplayNameInterface;
import org.ofbiz.ordermax.entity.PaymentMethodType;

/**
 *
 * @author BBS Auctions
 */
public class PaymentTypePaymentEntryPanel extends javax.swing.JPanel implements MouseListener, FocusListener {

    PaymentMethodType paymentMethodType = null;

    public PaymentMethodType getPaymentMethodType() {
        return paymentMethodType;
    }

    public void setPaymentMethodType(PaymentMethodType paymentMethodType) {
        this.paymentMethodType = paymentMethodType;
    }

    /**
     * Creates new form PaymentTypePaymentEntryPanel
     */
    public PaymentTypePaymentEntryPanel() {
        initComponents();
        txtPaymentAmount.addMouseListener(this);
        txtPaymentAmount.addFocusListener(this);
        txtPaymentReference.addMouseListener(this);
        txtPaymentReference.addFocusListener(this);
        //lbltypeName.addMouseListener(this);
        //lbltypeName.addFocusListener(this);
        //addMouseListener(this);
        //addFocusListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltypeName = new javax.swing.JLabel();
        txtPaymentAmount = new javax.swing.JTextField();
        txtPaymentReference = new javax.swing.JTextField();

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 0);
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);

        lbltypeName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltypeName.setText("jLabel1");
        lbltypeName.setMaximumSize(new java.awt.Dimension(0, 26));
        lbltypeName.setPreferredSize(new java.awt.Dimension(200, 26));
        add(lbltypeName);

        txtPaymentAmount.setMaximumSize(new java.awt.Dimension(0, 26));
        txtPaymentAmount.setPreferredSize(new java.awt.Dimension(100, 26));
        add(txtPaymentAmount);

        txtPaymentReference.setMaximumSize(new java.awt.Dimension(200, 26));
        txtPaymentReference.setPreferredSize(new java.awt.Dimension(200, 26));
        txtPaymentReference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentReferenceActionPerformed(evt);
            }
        });
        add(txtPaymentReference);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaymentReferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentReferenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentReferenceActionPerformed

    @Override
    public void focusGained(FocusEvent fe) {
        notifyListnersFocusGain();
        //System.out.println("Focus gained in JPanel" + paymentMethodType.getdisplayName(DisplayNameInterface.DisplayTypes.SHOW_NAME_ONLY));
    }

    @Override
    public void focusLost(FocusEvent fe) {
        // System.out.println("Focus lost in JPanel");
    }

    @Override
    public void mousePressed(MouseEvent me) {
        //requestFocus();
        notifyListnersFocusGain();
        //System.out.println("Mouse Pressed in JPanel" + paymentMethodType.getdisplayName(DisplayNameInterface.DisplayTypes.SHOW_NAME_ONLY));
    }

    @Override
    public void mouseReleased(MouseEvent me) {
    }

    @Override
    public void mouseClicked(MouseEvent me) {
//        notifyListnersFocusGain();
    }

    @Override
    public void mouseEntered(MouseEvent me) {
    }

    @Override
    public void mouseExited(MouseEvent me) {
    }

    private List<ActionListener> listeners = new ArrayList<ActionListener>();

    public void addActionListener(ActionListener listener) {
        listeners.add(listener);
    }

    public void removeActionListener(ActionListener listener) {
        listeners.remove(listener);
    }

    public void clearAllActionListener() {
        listeners.clear();
    }

    protected void notifyListnersFocusGain() {
        //notify 
        if (paymentMethodType != null) {
            ActionEvent event = new ActionEvent(this, 1, paymentMethodType.getpaymentMethodTypeId(), new Date().getTime(), 2);
            for (ActionListener listener : listeners) {
                listener.actionPerformed(event); // broadcast to all
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbltypeName;
    public javax.swing.JTextField txtPaymentAmount;
    public javax.swing.JTextField txtPaymentReference;
    // End of variables declaration//GEN-END:variables
}
