/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.reportdesigner.common;

import org.ofbiz.ordermax.base.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import static org.ofbiz.ordermax.base.ContainerPanelInterface.listeners;

/**
 *
 * @author siranjeev
 */
public class TwoPanelNonSizableReportContainerDlg extends javax.swing.JDialog implements ContainerPanelInterface {

    private PosReportPanel posReportPanel = null;
    /**
     * Creates new form ThreePanelContainerDlg
     */
    public TwoPanelNonSizableReportContainerDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        posReportPanel = new PosReportPanel();
       this.add(posReportPanel, BorderLayout.CENTER);
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(ContainerPanelInterface.ReturnStausType.RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public ContainerPanelInterface.ReturnStausType getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(ContainerPanelInterface.ReturnStausType.RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(ContainerPanelInterface.ReturnStausType retStatus) {
        returnStatus = retStatus;
        setVisible(false);
//        dispose();
    }
 //     public JPanel getPanelParent(){
 //       return parentPanel;
 //   }
    public JPanel getPanelDetail() {
        return posReportPanel.m_jPanelContainer;
    }

    public JPanel getPanelSelecton() {
        return null;
    }

    public JPanel getPanelButton() {
        return null;
    }

    public JTextField textField = null;

    @Override
    public void setVisible(boolean value) {
        super.setVisible(value);
        if (textField != null) {
            textField.requestFocusInWindow();
        }
    }
    
    @Override
    public void okButtonPressed() {                                         
        doClose(ReturnStausType.RET_OK);
    }                                        

    @Override
    public void cancelButtonPressed() {                                             
        doClose(ContainerPanelInterface.ReturnStausType.RET_CANCEL);
    }
    
    @Override
    public void addActionListener(ActionListener listener) {
        listeners.add(listener);
    }

    @Override
    public void removeActionListener(ActionListener listener) {
        listeners.remove(listener);
    }
    /**
     * @param args the command line arguments
     */
    public static void runPosReport() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TwoPanelNonSizableReportContainerDlg dialog = new TwoPanelNonSizableReportContainerDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
        public void setDividerLocation(int value){
//        jSplitPane1.setDividerLocation(value);
    }     
    public void setCaption(String title){
        
    }
    @Override
    public ContainerType getContainerType() {
        return ContainerType.TwoPanelNonSizableContainer;
    }      
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    private ContainerPanelInterface.ReturnStausType returnStatus = ContainerPanelInterface.ReturnStausType.RET_CANCEL;

    @Override
    public JPanel getPanelParent() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public PosReportPanel getPosReportPanel() {
        return posReportPanel;
    }

    public void setPosReportPanel(PosReportPanel posReportPanel) {
        this.posReportPanel = posReportPanel;
    }
}
