/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ofbiz.ordermax.dataimportexport;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import mvc.controller.ClearListModelAction;
import mvc.controller.LoadCustomerAction;
import mvc.controller.LoadOrderAction;
import mvc.controller.LoadOutstandingPurchaseInvoiceAction;
import org.ofbiz.ordermax.dataimportexport.loaders.LoadProductFromFileAction;
import mvc.controller.LoadProductPricesFromFileAction;
import mvc.controller.LoadSupplierAction;
import mvc.controller.LoadSupplierProductAction;
import mvc.controller.SwingWorkerProgressModel;
import mvc.data.Person;
import mvc.model.list.ListAdapterListModel;
import mvc.view.InvoiceCompositeOverviewPanel;
import mvc.view.LoadSpeedSimulationPanel;
import mvc.view.PartyLoadViewPanel;
import mvc.view.SwingWorkerBasedComponentVisibility;
import org.ofbiz.guiapp.xui.XuiSession;
import org.ofbiz.ordermax.composite.InvoiceComposite;
import org.ofbiz.ordermax.composite.Order;
import org.ofbiz.ordermax.composite.ShipmentReceiptComposite;
import org.ofbiz.ordermax.orderbase.purchaseorder.inventory.ReceiveInventoryPanel;

/**
 *
 * @author siranjeev
 */
public class PanelImportMain extends javax.swing.JPanel {
    private ListAdapterListModel<Person> personListModel = new ListAdapterListModel<Person>();
    private ListAdapterListModel<ShipmentReceiptComposite> ricListModel = new ListAdapterListModel<ShipmentReceiptComposite>();

    private ListAdapterListModel<Order> orderListModel = new ListAdapterListModel<Order>();
    private ListAdapterListModel<InvoiceComposite> invoiceCompositeListModel = new ListAdapterListModel<InvoiceComposite>();

    private SwingWorkerProgressModel swingWorkerProgressModel = new SwingWorkerProgressModel();
    private JProgressBar progressBar = new JProgressBar(swingWorkerProgressModel);

    private SwingWorkerBasedComponentVisibility swingWorkerBasedComponentVisibility = new SwingWorkerBasedComponentVisibility(
            progressBar);
    
    private ListAdapterListModel<Person> invoiceListModel = new ListAdapterListModel<Person>();

    private ReceiveInventoryPanel overviewPanel = new ReceiveInventoryPanel();
//    private OrderOverviewPanel orderOverviewPanel = new OrderOverviewPanel();
    private PartyLoadViewPanel partyLoadViewPanel = new PartyLoadViewPanel();
    private InvoiceCompositeOverviewPanel invoiceCompositePanel = new InvoiceCompositeOverviewPanel();
    private LoadSpeedSimulationPanel loadPersonSpeedSimulationPanel = new LoadSpeedSimulationPanel();
    private LoadSpeedSimulationPanel loadOrderSpeedSimulationPanel = new LoadSpeedSimulationPanel();

    private Component currentContent;
    XuiSession session = null;

    /**
     * Creates new form panelImportMain
     */
    public PanelImportMain() {
        initComponents();
    }
    /**
     *
     */
    private static final long serialVersionUID = 4353611743416911021L;



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
