/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.dataimportexport;

import java.awt.Dimension;
import java.awt.Font;
import java.text.MessageFormat;
import javax.swing.BoundedRangeModel;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JSlider;
import javax.swing.text.Document;
import mvc.controller.SwingWorkerProgressModel;
import mvc.model.BoundedRangeModel2DocumentAdapter;
import mvc.view.JLabelTextComponent;
import mvc.view.SwingWorkerBasedComponentVisibility;

/**
 *
 * @author siranjeev
 */
public class PanelImport extends javax.swing.JPanel {

    private static final int MIN_LOAD_SPEED_TICK_MS = 250;
    private static final int MAX_LOAD_SPEED_MS = 5000;
    private static final int INITIAL_LOAD_SPEED_MS = 500;

    public SwingWorkerProgressModel swingWorkerProgressModel = new SwingWorkerProgressModel();
    public JProgressBar progressBar = new JProgressBar(swingWorkerProgressModel);
    public SwingWorkerBasedComponentVisibility swingWorkerBasedComponentVisibility = new SwingWorkerBasedComponentVisibility(
            progressBar);

    /**
     * Creates new form PanelImport
     */
    public PanelImport() {
        initComponents();
        setLayout(null);
        loadPersonsSpeedModel.setMinimum(0);
        loadPersonsSpeedModel.setMaximum(MAX_LOAD_SPEED_MS);
        loadPersonsSpeedModel.setValue(INITIAL_LOAD_SPEED_MS);
        loadPersonsSpeedModel.setExtent(0);

        JSlider loadSpeedSlider = new JSlider();
        loadSpeedSlider.setMinorTickSpacing(MIN_LOAD_SPEED_TICK_MS);
        loadSpeedSlider.setSnapToTicks(true);
        loadSpeedSlider.setPaintTicks(true);
        loadSpeedSlider.setPaintLabels(true);
        loadSpeedSlider.setBounds(161, 12, 429, 43);
        loadSpeedSlider.setModel(loadPersonsSpeedModel);
        add(loadSpeedSlider);

        JLabelTextComponent selectedLoadSpeed = new JLabelTextComponent("");
        selectedLoadSpeed.setFont(new Font("Tahoma", Font.PLAIN, 12));
        selectedLoadSpeed.setBounds(10, 38, 138, 14);
        add(selectedLoadSpeed);

		// adapt the jLabel to the Document model to support MVC.
        MessageFormat speedLabelFormat = new MessageFormat(
                SIMULATION_SPEED_FORMAT);
        Document loadSpeedDocument = selectedLoadSpeed.getDocument();
        BoundedRangeModel2DocumentAdapter boundedRangeAdapter = new BoundedRangeModel2DocumentAdapter(
                loadSpeedDocument, speedLabelFormat);
        boundedRangeAdapter.bind(loadPersonsSpeedModel);

        JLabel label = new JLabel("Load Speed Simulation");
        label.setFont(new Font("Tahoma", Font.PLAIN, 12));
        label.setBounds(10, 11, 138, 14);
        add(label);

        setPreferredSize(new Dimension(600, 60));

    }
    private static final String SIMULATION_SPEED_FORMAT = "{0} ms";

    private BoundedRangeModel loadPersonsSpeedModel = new DefaultBoundedRangeModel();

    public BoundedRangeModel getPersonsLoadSpeedModel() {
        return loadPersonsSpeedModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
