/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.product;

import java.awt.Insets;
import javax.swing.JButton;

/**
 *
 * @author siranjeev
 */
public class ProductButtonPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductButtonPanel
     */
    public ProductButtonPanel() {
        initComponents();
    }

    @Override
    public Insets getInsets() {
        return new Insets(10, 5, 10, 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewDepartment = new javax.swing.JButton();
        btnNewBrandName = new javax.swing.JButton();
        btnNewProduct = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0, 5, 15));

        btnNewDepartment.setText("New Department");
        btnNewDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDepartmentActionPerformed(evt);
            }
        });
        add(btnNewDepartment);

        btnNewBrandName.setText("New Brand");
        btnNewBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBrandNameActionPerformed(evt);
            }
        });
        add(btnNewBrandName);

        btnNewProduct.setText("New Product");
        btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductActionPerformed(evt);
            }
        });
        add(btnNewProduct);
        add(jLabel2);

        btnLoad.setText("Reload");
        add(btnLoad);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);

        btnDelete.setText("Delete");
        add(btnDelete);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        add(cancelButton);

        okButton.setText("Ok");
        add(okButton);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDepartmentActionPerformed
        /*        editDepartmentId.setText("");
         editDepartmentName.setText("");
         comboPostalChanged(DEPARTMENT_TAB_INDEX);
         */
    }//GEN-LAST:event_btnNewDepartmentActionPerformed

    private void btnNewBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBrandNameActionPerformed
        /*        editBrandId.setText("");
         editBrandName.setText("");
         comboPostalChanged(BRAND_TAB_INDEX);
         * */
    }//GEN-LAST:event_btnNewBrandNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        /*Delegator delegator = (Delegator) session.getDelegator();
        
         if (jTabbedPane1.getSelectedIndex() == PRODUCT_TAB_INDEX) {
         if (isValidFields() == false) {
         return;
         }
         // save the changes
         save();
         loadProductTree();
         } else if (jTabbedPane1.getSelectedIndex() == BRAND_TAB_INDEX) {
         try {

         String depId = getDepartmentCode();
         String depName = getDepartmentName();
         String brandName = editBrandName.getText();

         String brandId = depId + "_" + brandName.replaceAll("\\s", "");

         if (brandId != null && brandId.length() > 20) {
         brandId = brandId.substring(0, 19);
         }
         editBrandId.setText(brandId);
         BrandTreeNode brandNode = new BrandTreeNode(brandId, brandName, false);
         //GenericValue genvalBrand = brandNode.loadDetails(brandId, delegator);
         //if (genvalBrand == null) {
         //                    brandNode.
         //                    brandNode.creatGenericValue(delegator);
         GenericValue brandCategory = PosProductHelper.getProductCategory(brandId, delegator);
         if (brandCategory == null) {
         delegator.create(PosProductHelper.createProductCategory(brandId, depId, "CATALOG_CATEGORY", brandName, delegator));
         }

         GenericValue rollUp = PosProductHelper.getProductCategoryRollup(brandId, depId, delegator);
         if (rollUp == null) {
         rollUp = PosProductHelper.createProductCategoryRollup(brandId, depId, delegator);
         delegator.create(rollUp);
         Debug.logInfo("create [createProductCategoryRollup] " + rollUp, module);
         }

         loadProductTree();
         //}

         //now add the node to tree

         } catch (GenericEntityException ex) {
         Logger.getLogger(ProductDetailEditDialog.class.getName()).log(Level.SEVERE, null, ex);
         }
         } else if (jTabbedPane1.getSelectedIndex() == DEPARTMENT_TAB_INDEX) {
         String depId = editDepartmentId.getText();
         String depName = editDepartmentName.getText();

         GenericValue brandCategory = PosProductHelper.getProductCategory(depId, delegator);
         if (brandCategory == null) {
         try {
         delegator.create(PosProductHelper.createProductCategory(depId, rootNode._id, "CATALOG_CATEGORY", depName, delegator));
         } catch (GenericEntityException ex) {
         Logger.getLogger(ProductDetailEditDialog.class.getName()).log(Level.SEVERE, null, ex);
         }
         }

         GenericValue rollUp = PosProductHelper.getProductCategoryRollup(depId, rootNode._id, delegator);
         if (rollUp == null) {
         try {
         rollUp = PosProductHelper.createProductCategoryRollup(depId, rootNode._id, delegator);
         delegator.create(rollUp);
         Debug.logInfo("create [createProductCategoryRollup] " + rollUp, module);
         } catch (GenericEntityException ex) {
         Logger.getLogger(ProductDetailEditDialog.class.getName()).log(Level.SEVERE, null, ex);
         }
         }

         loadProductTree();

         }
         */
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed
        /*clearProductDialogFields();
         comboPostalChanged(PRODUCT_TAB_INDEX);
         if (currTreeNode != null) {

         if (currTreeNode.getNodeName().equals(ProductTreeNode.ProdutNodeName)) {
         if (currTreeParentNode != null) {
         comboBrand.getModel().setSelectedItem(currTreeParentNode._name);
         }
         } else if (currTreeNode.getNodeName().equals(BrandTreeNode.BrandNodeName)) {
         comboBrand.getModel().setSelectedItem(currTreeNode._name);
         }

         //    protected TreeNode currTreeNode = null;
         //    protected TreeNode currTreeParentNode = null;

         }*/
    }//GEN-LAST:event_btnNewProductActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
//        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    public JButton getBtnNewBrandName() {
        return btnNewBrandName;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnNewDepartment() {
        return btnNewDepartment;
    }

    public JButton getBtnNewProduct() {
        return btnNewProduct;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public JButton getOkButton() {
        return okButton;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnNewBrandName;
    private javax.swing.JButton btnNewDepartment;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnLoad() {
        return btnLoad;
    }
}
