/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ofbiz.ordermax.party;

import java.text.ParseException;
import org.ofbiz.ordermax.composite.Account;
import org.ofbiz.ordermax.entity.PartyGroup;
import org.ofbiz.ordermax.utility.OrderMaxUtility;

/**
 *
 * @author siranjeev
 */
public class PartyGroupDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form PartyGroupDetailPanel
     */
    public PartyGroupDetailPanel() {
        initComponents();
    }

    private Account partyGroupAccount = null;

    public Account getPartyGroupAccount() {
        return partyGroupAccount;
    }

    public void setPartyGroupAccount(Account partyGroupAccount) {
        this.partyGroupAccount = partyGroupAccount;
    }

    public void setDialogFields() throws ParseException, java.text.ParseException {
        if (partyGroupAccount != null) {
            PartyGroup partygroup = partyGroupAccount.getPartyGroup();

            partyIdTextField.setText(OrderMaxUtility.getValidString(partygroup.getpartyId()));

            officeSiteNameTextField.setText(OrderMaxUtility.getValidString(partygroup.getofficeSiteName()));

//        annualRevenueTextField.setText(OrderMaxUtility.getValidString(partygroup.getannualRevenue()));
            groupNameTextField.setText(OrderMaxUtility.getValidString(partygroup.getgroupName()));

            commentsTextField.setText(OrderMaxUtility.getValidString(partygroup.getcomments()));

            groupNameLocalTextField.setText(OrderMaxUtility.getValidString(partygroup.getgroupNameLocal()));

            logoImageUrlTextField.setText(OrderMaxUtility.getValidString(partygroup.getlogoImageUrl()));

            tickerSymbolTextField.setText(OrderMaxUtility.getValidString(partygroup.gettickerSymbol()));
        }
//        numEmployeesTextField.setText(OrderMaxUtility.getValidString(partygroup.getnumEmployees()));
    }

    public void clearDialogFields() {

        partyIdTextField.setText("");

        officeSiteNameTextField.setText("");

//        annualRevenueTextField.setText(OrderMaxUtility.getValidString(partygroup.getannualRevenue()));
        groupNameTextField.setText("");

        commentsTextField.setText("");

        groupNameLocalTextField.setText("");

        logoImageUrlTextField.setText("");

        tickerSymbolTextField.setText("");

//        numEmployeesTextField.setText(OrderMaxUtility.getValidString(partygroup.getnumEmployees()));
    }

    public void getUIFields() throws ParseException, java.text.ParseException {
        PartyGroup partygroup = partyGroupAccount.getPartyGroup();
        partygroup.setpartyId(OrderMaxUtility.getValidString(partyIdTextField.getText()));

        partygroup.setofficeSiteName(OrderMaxUtility.getValidString(officeSiteNameTextField.getText()));

//        partygroup.setannualRevenue(OrderMaxUtility.getValidString(annualRevenueTextField.getText()));
        partygroup.setgroupName(OrderMaxUtility.getValidString(groupNameTextField.getText()));

        partygroup.setcomments(OrderMaxUtility.getValidString(commentsTextField.getText()));

        partygroup.setgroupNameLocal(OrderMaxUtility.getValidString(groupNameLocalTextField.getText()));

        partygroup.setlogoImageUrl(OrderMaxUtility.getValidString(logoImageUrlTextField.getText()));

        partygroup.settickerSymbol(OrderMaxUtility.getValidString(tickerSymbolTextField.getText()));

//        partygroup.setnumEmployees(OrderMaxUtility.getValidString(numEmployeesTextField.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        partyIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        groupNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        groupNameLocalTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tickerSymbolTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        officeSiteNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        annualRevenueTextField = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        numEmployeesTextField = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        commentsTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        logoImageUrlTextField = new javax.swing.JTextField();

        jLabel1.setText("Party Id:");

        jLabel2.setText("Group Name:");

        jLabel3.setText("Group Name Local:");

        jLabel4.setText("Ticker Symbol:");

        jLabel5.setText("Office Site Name:");

        jLabel6.setText("Annual Revenue:");

        jLabel7.setText("Number Of Employees:");

        jLabel8.setText("Comments:");

        jLabel9.setText("Logo Image URL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoImageUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numEmployeesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annualRevenueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(officeSiteNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tickerSymbolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupNameLocalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(partyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(groupNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(groupNameLocalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tickerSymbolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(officeSiteNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(annualRevenueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(numEmployeesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(commentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(logoImageUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox annualRevenueTextField;
    private javax.swing.JTextField commentsTextField;
    private javax.swing.JTextField groupNameLocalTextField;
    private javax.swing.JTextField groupNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField logoImageUrlTextField;
    private javax.swing.JComboBox numEmployeesTextField;
    private javax.swing.JTextField officeSiteNameTextField;
    public javax.swing.JTextField partyIdTextField;
    private javax.swing.JTextField tickerSymbolTextField;
    // End of variables declaration//GEN-END:variables
}
